/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.demos32;

import javax.swing.JOptionPane;

/**
 *
 * @author ROHIL
 */
public class Hospital_Inspection extends javax.swing.JFrame {

    /**
     * Creates new form Hospital_Inspection
     */
    public Hospital_Inspection() {
        initComponents();
    }
    
    // Array To Store Hospital Details (max 5)
    private String[] hospitalData = new String[5];
    private int currentIndex = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHospitalName = new javax.swing.JTextField();
        txtHospitalLocation = new javax.swing.JTextField();
        jcomboBox = new javax.swing.JComboBox<>();
        jbuttonSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jbuttonPrint = new javax.swing.JButton();
        jbuttonClear = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuSave = new javax.swing.JMenuItem();
        menuPrint = new javax.swing.JMenuItem();
        menuClear = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Hospital Location:");

        jLabel2.setText("Hospital Name:");

        jLabel3.setText("Years since inspection:");

        jcomboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Year", "2 Years", "3 Years", "4 Years", "5 Years" }));
        jcomboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboBoxActionPerformed(evt);
            }
        });

        jbuttonSave.setText("SAVE");
        jbuttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonSaveActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jbuttonPrint.setText("PRINT");
        jbuttonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonPrintActionPerformed(evt);
            }
        });

        jbuttonClear.setText("CLEAR");
        jbuttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonClearActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tools");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        menuSave.setText("Save");
        menuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveActionPerformed(evt);
            }
        });
        jMenu2.add(menuSave);

        menuPrint.setText("Print");
        jMenu2.add(menuPrint);

        menuClear.setText("Clear");
        menuClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClearActionPerformed(evt);
            }
        });
        jMenu2.add(menuClear);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jbuttonPrint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbuttonClear)
                        .addGap(50, 50, 50))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHospitalName)
                                    .addComponent(txtHospitalLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jcomboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbuttonSave)))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHospitalLocation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcomboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jbuttonSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbuttonPrint)
                    .addComponent(jbuttonClear))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcomboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboBoxActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void menuClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClearActionPerformed
        // TODO add your handling code here:
        // Reset to default state: 
        jcomboBox.setSelectedIndex(0); // Reverts back to first box
        txtHospitalName.setText("");
        txtHospitalLocation.setText("");
    }//GEN-LAST:event_menuClearActionPerformed

    private void jbuttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonClearActionPerformed
        // TODO add your handling code here:
        // Reset back to default values: 
        jcomboBox.setSelectedIndex(0); // Reverts back to original position
        txtHospitalName.setText("");
        txtHospitalLocation.setText("");
    }//GEN-LAST:event_jbuttonClearActionPerformed

    private void jbuttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonSaveActionPerformed
        // TODO add your handling code here:
        // Get Values From The form
        String hospitalName = txtHospitalName.getText();
        String hospitalLocation = txtHospitalLocation.getText();
        String yearsSinceInspection = (String) jcomboBox.getSelectedItem();
        
        // Check if we reached the maximum of 5 records
        if(currentIndex >= 5){
            JOptionPane.showMessageDialog(null, "Maximum inspection count reached", "Message",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
            //Save to Array
            hospitalData[currentIndex] = "Hospital Name: " + hospitalName + "\n"
                                                       + "Hospital Location: " + hospitalLocation  + "\n"
                                                        + "Years Since Last Inspection: " + yearsSinceInspection  + "\n";
            currentIndex++; // move to next position in array
            
            // Show a successful save output
            JOptionPane.showMessageDialog(null, "Saved Successfully \nRecode saved: " + currentIndex + "/5");
    }//GEN-LAST:event_jbuttonSaveActionPerformed

    private void menuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveActionPerformed
        // TODO add your handling code here:
         // Get Values From The form
        String hospitalName = txtHospitalName.getText();
        String hospitalLocation = txtHospitalLocation.getText();
        String yearsSinceInspection = (String) jcomboBox.getSelectedItem();
        
        if(currentIndex >= 5){
            JOptionPane.showMessageDialog(null, "Maximum inspecton count reached", "Message", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        //Save to the array
        hospitalData[currentIndex] = "Hospital Name: " + hospitalName  + "\n"
                                                  + "\nHospital Location: " + hospitalLocation  + "\n"
                                                   + "\nYears Since Last Inspection: " + yearsSinceInspection;
        
        
        
        currentIndex++; // Moves to the next position in the array
        
        // Show successful output of the array
        JOptionPane.showMessageDialog(null, "Saved Successfully \nRecord Saved: " + currentIndex + "/5");
        
    }//GEN-LAST:event_menuSaveActionPerformed

    private void jbuttonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonPrintActionPerformed
        // TODO add your handling code here:
        // Check if theres any data to print
        if(currentIndex == 0){
            JOptionPane.showMessageDialog(null, "No data to display! \nPlease save hospital details first", "No data", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Create a temporary array with only the saved data and no null values 
        String[] dataToDisplay = new String[currentIndex];
        for (int i = 0; i < currentIndex; i++) {
            dataToDisplay[i] = hospitalData[i];
        }
        
        // Create a String to display
        StringBuilder displayText = new StringBuilder();
        
        // Loop through array and get each saved record
        for (int i = 0; i < currentIndex; i++) {
          displayText.append(hospitalData[i]).append("");  // This gets data from array
          
        }
        
        //Display in the text area
        jTextArea1.setText(displayText.toString());
        System.out.println("*".repeat(25));
        
    }//GEN-LAST:event_jbuttonPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hospital_Inspection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hospital_Inspection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hospital_Inspection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hospital_Inspection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hospital_Inspection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbuttonClear;
    private javax.swing.JButton jbuttonPrint;
    private javax.swing.JButton jbuttonSave;
    private javax.swing.JComboBox<String> jcomboBox;
    private javax.swing.JMenuItem menuClear;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuPrint;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JTextField txtHospitalLocation;
    private javax.swing.JTextField txtHospitalName;
    // End of variables declaration//GEN-END:variables
}
